#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     touch,          sensorTouch)
#pragma config(Sensor, S4,     sonar,          sensorNone)
#pragma config(Motor,  motorA,          ziptiesMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C3_1,     raiseMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("joystickGame");
#pragma debuggerWindows("nxtLCDScreen");
#include "hitechnic-sensormux.h"
#include "hitechnic-irseeker-v2.h"

const tMUXSensor IRL = msensor_S2_3;
const tMUXSensor IRR = msensor_S2_4;

task main()
{
	eraseDisplay();

	if (HTSMUXreadSensorType(IRL) == HTSMUXIRSeeker) {
		writeDebugStreamLine("IRL is HTSMUXIRSeeker");
	}
	else if (HTSMUXreadSensorType(IRL) == HTSMUXIRSeekerNew ) {
		writeDebugStreamLine("IRL is HTSMUXIRSeekerNew");
	}
	else {
		writeDebugStreamLine("IRL is unknown");
	}

	if (HTSMUXreadSensorType(IRR) == HTSMUXIRSeeker) {
		writeDebugStreamLine("IRR is HTSMUXIRSeeker");
	}
	else if (HTSMUXreadSensorType(IRR) == HTSMUXIRSeekerNew ) {
		writeDebugStreamLine("IRR is HTSMUXIRSeekerNew");
	}
	else {
		writeDebugStreamLine("IRR is unknown");
	}

	while(true)
	{
		eraseDisplay();

		byte status = HTSMUXreadStatus(S1);
		displayTextLine(1, "Status: %d", status);
		if(status & HTSMUX_STAT_BATT ==	HTSMUX_STAT_BATT) {
			displayTextLine (1, "no power to MUX");
			PlaySound(soundException);
			// PlaySound(soundBeepBeep);
		}

		int currentIRL = HTIRS2readACDir(IRL);
		int currentIRR = HTIRS2readACDir(IRR);

		int irl1, irl2, irl3, irl4, irl5 = -1;
		int irr1, irr2, irr3, irr4, irr5 = -1;
		HTIRS2readAllACStrength(IRL, irl1, irl2, irl3, irl4, irl5 );
		HTIRS2readAllACStrength(IRR, irr1, irr2, irr3, irr4, irr5 );

		displayTextLine(2, "D %d %d", currentIRL, currentIRR);
		displayTextLine(3, "0 %d %d", irl1, irr1);
		displayTextLine(4, "1 %d %d", irl2, irr2);
		displayTextLine(5, "2 %d %d", irl3, irr3);
		displayTextLine(6, "3 %d %d", irl4, irr4);
		displayTextLine(7, "4 %d %d", irl5, irr5);
	}
}
