#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorNone)
#pragma config(Motor,  motorA,          ziptiesMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     raiseMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("debugStream");
#pragma debuggerWindows("joystickSimple");

#include "hitechnic-sensormux.h"
#include "hitechnic-irseeker-v2.h"

const tMUXSensor IRL = msensor_S2_3;
const tMUXSensor IRR = msensor_S2_4;

#include "JoystickDriver.c"
#include "Utilities.c"
#include "Driver.c"
#include "Manipulators.c"



task main()
{
//	waitForStart();
	allstop();

	// loop while we drive and run manipulatorss
	int previousIRL = -1;
	int previousIRR = -1;
	int previousSonar = -1;

	while(true)
	{
		//Get the Latest joystick values
		getJoystickSettings(joystick);
		//use the joystick settings to drive the wheels
		drive();
		//use the joystick settings to run the manipulators
		manipulators();

		int currentIRL = HTIRS2readACDir(IRL);
		int currentIRR = HTIRS2readACDir(IRR);
		if (currentIRL != previousIRL || currentIRR != previousIRR){
			displayTextLine(2, "IR is %d,%d", currentIRL, currentIRR);
			previousIRL = currentIRL;
			previousIRR = currentIRR;
		}
		int currentSonar = SensorValue(sonar);
		if (currentSonar != previousSonar){
			displayTextLine(4, "Sonar is %d", currentSonar);
			previousSonar = currentSonar;
		}

	}
}
